# Generated by Django 5.1.2 on 2024-10-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransferEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Token_id", models.CharField(max_length=100)),
                ("from_address", models.CharField(max_length=100)),
                ("to_address", models.CharField(max_length=100)),
                ("transaction_hash", models.CharField(max_length=100)),
                ("block_number", models.CharField(max_length=100)),
            ],
        ),
    ]
