# Generated by Django 5.1.2 on 2024-10-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nft", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferevent",
            name="Token_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="transferevent",
            name="block_number",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="transferevent",
            name="from_address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="transferevent",
            name="to_address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="transferevent",
            name="transaction_hash",
            field=models.CharField(max_length=255),
        ),
    ]
