# Generated by Django 5.1.2 on 2024-10-17 01:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nft", "0002_alter_transferevent_token_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transferevent",
            old_name="Token_id",
            new_name="token_id",
        ),
    ]
