# Generated by Django 5.1.2 on 2024-10-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nft", "0003_rename_token_id_transferevent_token_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferevent",
            name="block_number",
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name="transferevent",
            name="token_id",
            field=models.IntegerField(),
        ),
    ]
