# Generated by Django 5.1.2 on 2024-10-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nft", "0004_alter_transferevent_block_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferevent",
            name="block_number",
            field=models.IntegerField(),
        ),
    ]
